todo_core/urls.py
from django.urls import path

from todo_core.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_do_undo
)

urlpatterns = [
    path("", TaskListView.as_view(), name="todo_list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/toggle/", toggle_do_undo, name="toggle-task"),
    path("tags", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]

app_name = "todo_core"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_core.urls", namespace="todo_core"))
]

todo_core/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name", ]

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "-created_time", ]

    def __str__(self):
        return self.content

todo_core/forms.py
from django import forms

from todo_core.models import Tag, Task


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(),
        help_text="Example: 2024-01-01 23:59",
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_core/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo_core.forms import TaskForm
from todo_core.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_core:todo_list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_core:todo_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_core:todo_list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_core:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_core:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_core:tag_list")


def toggle_do_undo(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo_core:todo_list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
    <title>TODO list</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_core:todo_list' %}">Home page</a></li>
  <li class="list-group-item"><a href="{% url 'todo_core:tag_list' %}">Tags</a></li>
</ul>

templates/todo_core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag: {{ tag.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_core/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_core/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a style="float: right" href="{% url 'todo_core:tag_create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a class="btn btn-secondary" href="{% url 'todo_core:tag_update' pk=tag.id %}">Update</a></td>
          <td><a class="btn btn-secondary" href="{% url 'todo_core:tag_delete' pk=tag.id %}">Delete</a></td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/todo_core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task: {{ task.content }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_core/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_core/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a style="float: right" href="{% url 'todo_core:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>

  {% if task_list %}
    {% for task in task_list %}
      <br>
      <h4>{{ task.content }}
        {% if task.is_completed %}
          <span style="color: green">Done</span>
        {% else %}
          <span style="color: red">Not done</span>
        {% endif %}
        {% if task.is_completed %}
          <a style="float: right" href="{% url 'todo_core:toggle-task' pk=task.id %}" class="btn btn-secondary link-to-page">
            Undo
          </a>
        {% else %}
          <a style="float: right" href="{% url 'todo_core:toggle-task' pk=task.id %}" class="btn btn-success link-to-page">
            Complete
          </a>
        {% endif %}
      </h4>
      <h6>Created: {{ task.created_time|date:"F j, Y, h:i a" }}
        <span style="color: brown">
          {% if task.deadline %}
            Deadline: {{ task.deadline|date:"F j, Y, h:i a" }}
          {% endif %}
        </span>
      </h6>
      <p>
        Tags: {% for tag in task.tags.all %} {{ tag.name }} {% endfor %}
        <a href="{% url 'todo_core:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'todo_core:task-delete' pk=task.id %}">Delete</a>
      </p>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no tasks in list</p>
  {% endif %}
{% endblock %}